print ("Tugas Python")
print ()()
nama = input("Masukan nama Anda :")
panggilan = input("Masukan Panggilan :")
nim = input("Masukan NIM :")
tglhr = input("Masukan Tanggal Lahir :")
tmlhr = input("Masukan Tempat Lahir :")
tlpn = input ("Masukan Nomer Telepon :")
alamat = input ("Masukan Alamat :")
umur = ("Masukan Umur Anda :")
